### ISSUE TITLE
reset 후 키보드 값이 변경 안됨.

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#16]
https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/blob/29eb17d9bac7b08f1eb9e1cbf87cd844c01d0cdc/src/main/java/seoultech/se/tetris/menu/SettingMenu.java#L73

reset 후 키보드 값이 변경 안됨.

다시 시작하면 됨. reload 해야할 듯

**Comment by UnGwan** [comment]
2a1c9b2a2ca97fba446ebf12a53afd161593be8c
