### ISSUE TITLE
Fix: line erase 횟수별 아이템 생성 동작 확인

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#23]
Fix: line erase 횟수별 아이템 생성 동작 확인

중간 평가 때 5회마다 아이템 생성됨. (requirement는 10회)

**Comment by ha4219** [comment]
https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/blob/59439cde1f007fc7dbc708a076bd9f0a11d5de54/src/main/java/seoultech/se/tetris/component/board/Board.java#L67

https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/blob/59439cde1f007fc7dbc708a076bd9f0a11d5de54/src/main/java/seoultech/se/tetris/component/board/ItemBoard.java#L323-L326


따라서 Item block이 5줄을 지울 때마다 생성됨. 효근이 첨삭해야할 듯 @HIGeuni

**Comment by HiGeuni** [comment]
https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/commit/a02508cda60f3ca6d637c90d632713c934cf123f
