### ISSUE TITLE
[WEEK 12] FIX previous error

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#27]
- 테트리스 게임 보드 글자 width 안맞는 error
- 키 설정 문자 코드 mapping 문제

**Comment by UnGwan** [comment]
기존에 macos에서는 방향키 및 특정 문자 모양이 우리가 원하는대로 보였으나 윈도우에서는 랜더링 방식이 달라서 글자가 깨지거나 특히 방향키의 경우 -> 의 경우 "Right"와 같이 랜더링되는 문제가 있음.

**Comment by ha4219** [comment]
미해결 다음주로 넘김
