### ISSUE TITLE
[Week 12] TEST java version

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#29]
- 버전에 따른 테스트

**Comment by HiGeuni** [comment]
[src/main/java/seoultech/se/tetris/component/JSONLoader.java](https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/commit/d9765a344b281e7bfc2386f5dc71705e25388efc)

**Comment by HiGeuni** [comment]
readBytesAll() 이 jre 1.9 이상부터 되는 것으로 확인

JSONLoader.java에서 그 부분을 수정함.

각 버전에 대해서 테스트를 한 결과 다른 부분에선 문제 발견 x

하지만 처음 시작 시, 매핑된 키들이 안뜨는 것은 여전했음.
