### ISSUE TITLE
[Week 13] FIX 키맵핑(방향키)

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#30]
[Week 13] FIX 키맵핑(방향키)

**Comment by UnGwan** [comment]
![image](https://user-images.githubusercontent.com/90377826/169020751-e2c95c2a-ecdb-4a79-a4ae-1139af61cc07.png)
동하가 디코로 준 텍스트로 적용해볼라 했는데 맥에선 잘되나 윈도우로 돌리면 다음과 같은 에러가 뜨면서 아예 테트리스 실행이 안됨.

**Comment by ha4219** [comment]
![image](https://user-images.githubusercontent.com/38957165/169049815-858a1be2-0d9e-49d6-9f7a-f22e1d1b9001.png)
![image](https://user-images.githubusercontent.com/38957165/169049828-27c74e82-b996-4d33-91ee-de8643e778e5.png)
인코딩 문제 

아래 사이트 참고 
https://www.lesstif.com/java/intellij-file-console-encoding-121012310.html
