### ISSUE TITLE
[Week 14] 한글 encoding 문제 (효근)

### ISSUE THREAD

**Issue by ha4219** [SE-Team6/SE_Project_Tetris_Java_Swing#43]
- 한글 encoding 문제 (효근)
  - score board update 시 한글 입력시 화면이 안보임.
  - score board 에 저장된 값 중 한글 값이 있으면 네모로 깨져서 보임.

**Comment by HiGeuni** [comment]
(solved) [Week 14] 한글 encoding 문제
![image](https://user-images.githubusercontent.com/59858440/170274492-07700a2d-6cb5-45ad-b625-838f7e66380a.png)
![image](https://user-images.githubusercontent.com/59858440/170274548-b413ee57-2d25-4f68-ace0-e2308163a8f5.png)

https://github.com/SE-Team6/SE_Project_Tetris_Java_Swing/commit/a21240b81c81c2c3a0373a9c94a3e26c01f5e48c
